// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package iamdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type IamUser struct {
	ID        pgtype.UUID
	Email     string
	Phone     pgtype.Text
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
