// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package iamdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIAMUser = `-- name: CreateIAMUser :one
INSERT INTO iam_users (
        id,
        email,
        phone,
        status,
        created_at,
        updated_at
    )
VALUES ($1, $2, $3, $4, now(), now())
RETURNING id, email, phone, status, created_at, updated_at
`

type CreateIAMUserParams struct {
	ID     pgtype.UUID
	Email  string
	Phone  pgtype.Text
	Status string
}

func (q *Queries) CreateIAMUser(ctx context.Context, arg CreateIAMUserParams) (IamUser, error) {
	row := q.db.QueryRow(ctx, createIAMUser,
		arg.ID,
		arg.Email,
		arg.Phone,
		arg.Status,
	)
	var i IamUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIAMUser = `-- name: DeleteIAMUser :exec
UPDATE iam_users
SET status = 'DELETED',
    updated_at = now()
WHERE id = $1
`

func (q *Queries) DeleteIAMUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteIAMUser, id)
	return err
}

const getIAMUserByEmail = `-- name: GetIAMUserByEmail :one
SELECT id, email, phone, status, created_at, updated_at
FROM iam_users
WHERE email = $1
`

func (q *Queries) GetIAMUserByEmail(ctx context.Context, email string) (IamUser, error) {
	row := q.db.QueryRow(ctx, getIAMUserByEmail, email)
	var i IamUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIAMUserByID = `-- name: GetIAMUserByID :one
SELECT id, email, phone, status, created_at, updated_at
FROM iam_users
WHERE id = $1
`

func (q *Queries) GetIAMUserByID(ctx context.Context, id pgtype.UUID) (IamUser, error) {
	row := q.db.QueryRow(ctx, getIAMUserByID, id)
	var i IamUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIAMUsers = `-- name: ListIAMUsers :many
SELECT id, email, phone, status, created_at, updated_at
FROM iam_users
ORDER BY created_at DESC
`

func (q *Queries) ListIAMUsers(ctx context.Context) ([]IamUser, error) {
	rows, err := q.db.Query(ctx, listIAMUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IamUser
	for rows.Next() {
		var i IamUser
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Phone,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIAMUser = `-- name: UpdateIAMUser :one
UPDATE iam_users
SET email = $2,
    phone = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, email, phone, status, created_at, updated_at
`

type UpdateIAMUserParams struct {
	ID    pgtype.UUID
	Email string
	Phone pgtype.Text
}

func (q *Queries) UpdateIAMUser(ctx context.Context, arg UpdateIAMUserParams) (IamUser, error) {
	row := q.db.QueryRow(ctx, updateIAMUser, arg.ID, arg.Email, arg.Phone)
	var i IamUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIAMUserStatus = `-- name: UpdateIAMUserStatus :exec
UPDATE iam_users
SET status = $2,
    updated_at = now()
WHERE id = $1
`

type UpdateIAMUserStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateIAMUserStatus(ctx context.Context, arg UpdateIAMUserStatusParams) error {
	_, err := q.db.Exec(ctx, updateIAMUserStatus, arg.ID, arg.Status)
	return err
}
