/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchoolRouteImport } from './routes/school'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SchoolTimetableRouteImport } from './routes/school.timetable'
import { Route as SchoolTenantConfigurationRouteImport } from './routes/school.tenant-configuration'
import { Route as SchoolStudentsRouteImport } from './routes/school.students'
import { Route as SchoolStaffRouteImport } from './routes/school.staff'
import { Route as SchoolSettingsRouteImport } from './routes/school.settings'
import { Route as SchoolNemisRouteImport } from './routes/school.nemis'
import { Route as SchoolMpesaRouteImport } from './routes/school.mpesa'
import { Route as SchoolFinanceRouteImport } from './routes/school.finance'
import { Route as SchoolExamsRouteImport } from './routes/school.exams'
import { Route as SchoolDashboardRouteImport } from './routes/school.dashboard'
import { Route as SchoolCbcRouteImport } from './routes/school.cbc'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminSchoolsRouteImport } from './routes/admin.schools'
import { Route as AdminOnboardingRouteImport } from './routes/admin.onboarding'
import { Route as AdminGovernanceRouteImport } from './routes/admin.governance'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as SchoolStudentsIndexRouteImport } from './routes/school.students.index'
import { Route as SchoolStaffIndexRouteImport } from './routes/school.staff.index'
import { Route as SchoolMpesaIndexRouteImport } from './routes/school.mpesa.index'
import { Route as SchoolFinanceIndexRouteImport } from './routes/school.finance.index'
import { Route as AdminSupportIndexRouteImport } from './routes/admin.support.index'
import { Route as AdminSchoolsIndexRouteImport } from './routes/admin.schools.index'
import { Route as AdminOnboardingIndexRouteImport } from './routes/admin.onboarding.index'
import { Route as AdminBillingIndexRouteImport } from './routes/admin.billing.index'
import { Route as AdminAnnouncementsIndexRouteImport } from './routes/admin.announcements.index'
import { Route as SchoolStudentsTransfersRouteImport } from './routes/school.students.transfers'
import { Route as SchoolStudentsGuardiansRouteImport } from './routes/school.students.guardians'
import { Route as SchoolStudentsAdmissionsRouteImport } from './routes/school.students.admissions'
import { Route as SchoolStudentsStudentIdRouteImport } from './routes/school.students.$studentId'
import { Route as SchoolStaffWorkloadRouteImport } from './routes/school.staff.workload'
import { Route as SchoolStaffSubjectAllocationRouteImport } from './routes/school.staff.subject-allocation'
import { Route as SchoolStaffScheduleRouteImport } from './routes/school.staff.schedule'
import { Route as SchoolStaffDepartmentsRouteImport } from './routes/school.staff.departments'
import { Route as SchoolStaffTeacherIdRouteImport } from './routes/school.staff.$teacherId'
import { Route as SchoolMpesaTransactionIdRouteImport } from './routes/school.mpesa.$transactionId'
import { Route as SchoolFinanceDefaultersRouteImport } from './routes/school.finance.defaulters'
import { Route as SchoolFinanceReceiptIdRouteImport } from './routes/school.finance.$receiptId'
import { Route as AdminSupportTicketIdRouteImport } from './routes/admin.support.$ticketId'
import { Route as AdminSchoolsSchoolIdRouteImport } from './routes/admin.schools.$schoolId'
import { Route as AdminOnboardingOnboardingIdRouteImport } from './routes/admin.onboarding.$onboardingId'
import { Route as AdminAnnouncementsAnnouncementIdRouteImport } from './routes/admin.announcements.$announcementId'
import { Route as AdminBillingSubscriptionsSubscriptionIdRouteImport } from './routes/admin.billing.subscriptions.$subscriptionId'
import { Route as AdminBillingPlansPlanIdRouteImport } from './routes/admin.billing.plans.$planId'
import { Route as AdminBillingPaymentsPaymentIdRouteImport } from './routes/admin.billing.payments.$paymentId'
import { Route as AdminBillingInvoicesInvoiceIdRouteImport } from './routes/admin.billing.invoices.$invoiceId'

const SchoolRoute = SchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolTimetableRoute = SchoolTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolTenantConfigurationRoute =
  SchoolTenantConfigurationRouteImport.update({
    id: '/tenant-configuration',
    path: '/tenant-configuration',
    getParentRoute: () => SchoolRoute,
  } as any)
const SchoolStudentsRoute = SchoolStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolStaffRoute = SchoolStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolSettingsRoute = SchoolSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolNemisRoute = SchoolNemisRouteImport.update({
  id: '/nemis',
  path: '/nemis',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolMpesaRoute = SchoolMpesaRouteImport.update({
  id: '/mpesa',
  path: '/mpesa',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolFinanceRoute = SchoolFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolExamsRoute = SchoolExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolDashboardRoute = SchoolDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolCbcRoute = SchoolCbcRouteImport.update({
  id: '/cbc',
  path: '/cbc',
  getParentRoute: () => SchoolRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchoolsRoute = AdminSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOnboardingRoute = AdminOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGovernanceRoute = AdminGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const SchoolStudentsIndexRoute = SchoolStudentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SchoolStudentsRoute,
} as any)
const SchoolStaffIndexRoute = SchoolStaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SchoolStaffRoute,
} as any)
const SchoolMpesaIndexRoute = SchoolMpesaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SchoolMpesaRoute,
} as any)
const SchoolFinanceIndexRoute = SchoolFinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SchoolFinanceRoute,
} as any)
const AdminSupportIndexRoute = AdminSupportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSupportRoute,
} as any)
const AdminSchoolsIndexRoute = AdminSchoolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSchoolsRoute,
} as any)
const AdminOnboardingIndexRoute = AdminOnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminOnboardingRoute,
} as any)
const AdminBillingIndexRoute = AdminBillingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminBillingRoute,
} as any)
const AdminAnnouncementsIndexRoute = AdminAnnouncementsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAnnouncementsRoute,
} as any)
const SchoolStudentsTransfersRoute = SchoolStudentsTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => SchoolStudentsRoute,
} as any)
const SchoolStudentsGuardiansRoute = SchoolStudentsGuardiansRouteImport.update({
  id: '/guardians',
  path: '/guardians',
  getParentRoute: () => SchoolStudentsRoute,
} as any)
const SchoolStudentsAdmissionsRoute =
  SchoolStudentsAdmissionsRouteImport.update({
    id: '/admissions',
    path: '/admissions',
    getParentRoute: () => SchoolStudentsRoute,
  } as any)
const SchoolStudentsStudentIdRoute = SchoolStudentsStudentIdRouteImport.update({
  id: '/$studentId',
  path: '/$studentId',
  getParentRoute: () => SchoolStudentsRoute,
} as any)
const SchoolStaffWorkloadRoute = SchoolStaffWorkloadRouteImport.update({
  id: '/workload',
  path: '/workload',
  getParentRoute: () => SchoolStaffRoute,
} as any)
const SchoolStaffSubjectAllocationRoute =
  SchoolStaffSubjectAllocationRouteImport.update({
    id: '/subject-allocation',
    path: '/subject-allocation',
    getParentRoute: () => SchoolStaffRoute,
  } as any)
const SchoolStaffScheduleRoute = SchoolStaffScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => SchoolStaffRoute,
} as any)
const SchoolStaffDepartmentsRoute = SchoolStaffDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => SchoolStaffRoute,
} as any)
const SchoolStaffTeacherIdRoute = SchoolStaffTeacherIdRouteImport.update({
  id: '/$teacherId',
  path: '/$teacherId',
  getParentRoute: () => SchoolStaffRoute,
} as any)
const SchoolMpesaTransactionIdRoute =
  SchoolMpesaTransactionIdRouteImport.update({
    id: '/$transactionId',
    path: '/$transactionId',
    getParentRoute: () => SchoolMpesaRoute,
  } as any)
const SchoolFinanceDefaultersRoute = SchoolFinanceDefaultersRouteImport.update({
  id: '/defaulters',
  path: '/defaulters',
  getParentRoute: () => SchoolFinanceRoute,
} as any)
const SchoolFinanceReceiptIdRoute = SchoolFinanceReceiptIdRouteImport.update({
  id: '/$receiptId',
  path: '/$receiptId',
  getParentRoute: () => SchoolFinanceRoute,
} as any)
const AdminSupportTicketIdRoute = AdminSupportTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => AdminSupportRoute,
} as any)
const AdminSchoolsSchoolIdRoute = AdminSchoolsSchoolIdRouteImport.update({
  id: '/$schoolId',
  path: '/$schoolId',
  getParentRoute: () => AdminSchoolsRoute,
} as any)
const AdminOnboardingOnboardingIdRoute =
  AdminOnboardingOnboardingIdRouteImport.update({
    id: '/$onboardingId',
    path: '/$onboardingId',
    getParentRoute: () => AdminOnboardingRoute,
  } as any)
const AdminAnnouncementsAnnouncementIdRoute =
  AdminAnnouncementsAnnouncementIdRouteImport.update({
    id: '/$announcementId',
    path: '/$announcementId',
    getParentRoute: () => AdminAnnouncementsRoute,
  } as any)
const AdminBillingSubscriptionsSubscriptionIdRoute =
  AdminBillingSubscriptionsSubscriptionIdRouteImport.update({
    id: '/subscriptions/$subscriptionId',
    path: '/subscriptions/$subscriptionId',
    getParentRoute: () => AdminBillingRoute,
  } as any)
const AdminBillingPlansPlanIdRoute = AdminBillingPlansPlanIdRouteImport.update({
  id: '/plans/$planId',
  path: '/plans/$planId',
  getParentRoute: () => AdminBillingRoute,
} as any)
const AdminBillingPaymentsPaymentIdRoute =
  AdminBillingPaymentsPaymentIdRouteImport.update({
    id: '/payments/$paymentId',
    path: '/payments/$paymentId',
    getParentRoute: () => AdminBillingRoute,
  } as any)
const AdminBillingInvoicesInvoiceIdRoute =
  AdminBillingInvoicesInvoiceIdRouteImport.update({
    id: '/invoices/$invoiceId',
    path: '/invoices/$invoiceId',
    getParentRoute: () => AdminBillingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/school': typeof SchoolRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRouteWithChildren
  '/admin/billing': typeof AdminBillingRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/governance': typeof AdminGovernanceRoute
  '/admin/onboarding': typeof AdminOnboardingRouteWithChildren
  '/admin/schools': typeof AdminSchoolsRouteWithChildren
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRouteWithChildren
  '/school/cbc': typeof SchoolCbcRoute
  '/school/dashboard': typeof SchoolDashboardRoute
  '/school/exams': typeof SchoolExamsRoute
  '/school/finance': typeof SchoolFinanceRouteWithChildren
  '/school/mpesa': typeof SchoolMpesaRouteWithChildren
  '/school/nemis': typeof SchoolNemisRoute
  '/school/settings': typeof SchoolSettingsRoute
  '/school/staff': typeof SchoolStaffRouteWithChildren
  '/school/students': typeof SchoolStudentsRouteWithChildren
  '/school/tenant-configuration': typeof SchoolTenantConfigurationRoute
  '/school/timetable': typeof SchoolTimetableRoute
  '/admin/announcements/$announcementId': typeof AdminAnnouncementsAnnouncementIdRoute
  '/admin/onboarding/$onboardingId': typeof AdminOnboardingOnboardingIdRoute
  '/admin/schools/$schoolId': typeof AdminSchoolsSchoolIdRoute
  '/admin/support/$ticketId': typeof AdminSupportTicketIdRoute
  '/school/finance/$receiptId': typeof SchoolFinanceReceiptIdRoute
  '/school/finance/defaulters': typeof SchoolFinanceDefaultersRoute
  '/school/mpesa/$transactionId': typeof SchoolMpesaTransactionIdRoute
  '/school/staff/$teacherId': typeof SchoolStaffTeacherIdRoute
  '/school/staff/departments': typeof SchoolStaffDepartmentsRoute
  '/school/staff/schedule': typeof SchoolStaffScheduleRoute
  '/school/staff/subject-allocation': typeof SchoolStaffSubjectAllocationRoute
  '/school/staff/workload': typeof SchoolStaffWorkloadRoute
  '/school/students/$studentId': typeof SchoolStudentsStudentIdRoute
  '/school/students/admissions': typeof SchoolStudentsAdmissionsRoute
  '/school/students/guardians': typeof SchoolStudentsGuardiansRoute
  '/school/students/transfers': typeof SchoolStudentsTransfersRoute
  '/admin/announcements/': typeof AdminAnnouncementsIndexRoute
  '/admin/billing/': typeof AdminBillingIndexRoute
  '/admin/onboarding/': typeof AdminOnboardingIndexRoute
  '/admin/schools/': typeof AdminSchoolsIndexRoute
  '/admin/support/': typeof AdminSupportIndexRoute
  '/school/finance/': typeof SchoolFinanceIndexRoute
  '/school/mpesa/': typeof SchoolMpesaIndexRoute
  '/school/staff/': typeof SchoolStaffIndexRoute
  '/school/students/': typeof SchoolStudentsIndexRoute
  '/admin/billing/invoices/$invoiceId': typeof AdminBillingInvoicesInvoiceIdRoute
  '/admin/billing/payments/$paymentId': typeof AdminBillingPaymentsPaymentIdRoute
  '/admin/billing/plans/$planId': typeof AdminBillingPlansPlanIdRoute
  '/admin/billing/subscriptions/$subscriptionId': typeof AdminBillingSubscriptionsSubscriptionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/school': typeof SchoolRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/governance': typeof AdminGovernanceRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/school/cbc': typeof SchoolCbcRoute
  '/school/dashboard': typeof SchoolDashboardRoute
  '/school/exams': typeof SchoolExamsRoute
  '/school/nemis': typeof SchoolNemisRoute
  '/school/settings': typeof SchoolSettingsRoute
  '/school/tenant-configuration': typeof SchoolTenantConfigurationRoute
  '/school/timetable': typeof SchoolTimetableRoute
  '/admin/announcements/$announcementId': typeof AdminAnnouncementsAnnouncementIdRoute
  '/admin/onboarding/$onboardingId': typeof AdminOnboardingOnboardingIdRoute
  '/admin/schools/$schoolId': typeof AdminSchoolsSchoolIdRoute
  '/admin/support/$ticketId': typeof AdminSupportTicketIdRoute
  '/school/finance/$receiptId': typeof SchoolFinanceReceiptIdRoute
  '/school/finance/defaulters': typeof SchoolFinanceDefaultersRoute
  '/school/mpesa/$transactionId': typeof SchoolMpesaTransactionIdRoute
  '/school/staff/$teacherId': typeof SchoolStaffTeacherIdRoute
  '/school/staff/departments': typeof SchoolStaffDepartmentsRoute
  '/school/staff/schedule': typeof SchoolStaffScheduleRoute
  '/school/staff/subject-allocation': typeof SchoolStaffSubjectAllocationRoute
  '/school/staff/workload': typeof SchoolStaffWorkloadRoute
  '/school/students/$studentId': typeof SchoolStudentsStudentIdRoute
  '/school/students/admissions': typeof SchoolStudentsAdmissionsRoute
  '/school/students/guardians': typeof SchoolStudentsGuardiansRoute
  '/school/students/transfers': typeof SchoolStudentsTransfersRoute
  '/admin/announcements': typeof AdminAnnouncementsIndexRoute
  '/admin/billing': typeof AdminBillingIndexRoute
  '/admin/onboarding': typeof AdminOnboardingIndexRoute
  '/admin/schools': typeof AdminSchoolsIndexRoute
  '/admin/support': typeof AdminSupportIndexRoute
  '/school/finance': typeof SchoolFinanceIndexRoute
  '/school/mpesa': typeof SchoolMpesaIndexRoute
  '/school/staff': typeof SchoolStaffIndexRoute
  '/school/students': typeof SchoolStudentsIndexRoute
  '/admin/billing/invoices/$invoiceId': typeof AdminBillingInvoicesInvoiceIdRoute
  '/admin/billing/payments/$paymentId': typeof AdminBillingPaymentsPaymentIdRoute
  '/admin/billing/plans/$planId': typeof AdminBillingPlansPlanIdRoute
  '/admin/billing/subscriptions/$subscriptionId': typeof AdminBillingSubscriptionsSubscriptionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/school': typeof SchoolRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRouteWithChildren
  '/admin/billing': typeof AdminBillingRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/governance': typeof AdminGovernanceRoute
  '/admin/onboarding': typeof AdminOnboardingRouteWithChildren
  '/admin/schools': typeof AdminSchoolsRouteWithChildren
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRouteWithChildren
  '/school/cbc': typeof SchoolCbcRoute
  '/school/dashboard': typeof SchoolDashboardRoute
  '/school/exams': typeof SchoolExamsRoute
  '/school/finance': typeof SchoolFinanceRouteWithChildren
  '/school/mpesa': typeof SchoolMpesaRouteWithChildren
  '/school/nemis': typeof SchoolNemisRoute
  '/school/settings': typeof SchoolSettingsRoute
  '/school/staff': typeof SchoolStaffRouteWithChildren
  '/school/students': typeof SchoolStudentsRouteWithChildren
  '/school/tenant-configuration': typeof SchoolTenantConfigurationRoute
  '/school/timetable': typeof SchoolTimetableRoute
  '/admin/announcements/$announcementId': typeof AdminAnnouncementsAnnouncementIdRoute
  '/admin/onboarding/$onboardingId': typeof AdminOnboardingOnboardingIdRoute
  '/admin/schools/$schoolId': typeof AdminSchoolsSchoolIdRoute
  '/admin/support/$ticketId': typeof AdminSupportTicketIdRoute
  '/school/finance/$receiptId': typeof SchoolFinanceReceiptIdRoute
  '/school/finance/defaulters': typeof SchoolFinanceDefaultersRoute
  '/school/mpesa/$transactionId': typeof SchoolMpesaTransactionIdRoute
  '/school/staff/$teacherId': typeof SchoolStaffTeacherIdRoute
  '/school/staff/departments': typeof SchoolStaffDepartmentsRoute
  '/school/staff/schedule': typeof SchoolStaffScheduleRoute
  '/school/staff/subject-allocation': typeof SchoolStaffSubjectAllocationRoute
  '/school/staff/workload': typeof SchoolStaffWorkloadRoute
  '/school/students/$studentId': typeof SchoolStudentsStudentIdRoute
  '/school/students/admissions': typeof SchoolStudentsAdmissionsRoute
  '/school/students/guardians': typeof SchoolStudentsGuardiansRoute
  '/school/students/transfers': typeof SchoolStudentsTransfersRoute
  '/admin/announcements/': typeof AdminAnnouncementsIndexRoute
  '/admin/billing/': typeof AdminBillingIndexRoute
  '/admin/onboarding/': typeof AdminOnboardingIndexRoute
  '/admin/schools/': typeof AdminSchoolsIndexRoute
  '/admin/support/': typeof AdminSupportIndexRoute
  '/school/finance/': typeof SchoolFinanceIndexRoute
  '/school/mpesa/': typeof SchoolMpesaIndexRoute
  '/school/staff/': typeof SchoolStaffIndexRoute
  '/school/students/': typeof SchoolStudentsIndexRoute
  '/admin/billing/invoices/$invoiceId': typeof AdminBillingInvoicesInvoiceIdRoute
  '/admin/billing/payments/$paymentId': typeof AdminBillingPaymentsPaymentIdRoute
  '/admin/billing/plans/$planId': typeof AdminBillingPlansPlanIdRoute
  '/admin/billing/subscriptions/$subscriptionId': typeof AdminBillingSubscriptionsSubscriptionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/school'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/billing'
    | '/admin/dashboard'
    | '/admin/governance'
    | '/admin/onboarding'
    | '/admin/schools'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/support'
    | '/school/cbc'
    | '/school/dashboard'
    | '/school/exams'
    | '/school/finance'
    | '/school/mpesa'
    | '/school/nemis'
    | '/school/settings'
    | '/school/staff'
    | '/school/students'
    | '/school/tenant-configuration'
    | '/school/timetable'
    | '/admin/announcements/$announcementId'
    | '/admin/onboarding/$onboardingId'
    | '/admin/schools/$schoolId'
    | '/admin/support/$ticketId'
    | '/school/finance/$receiptId'
    | '/school/finance/defaulters'
    | '/school/mpesa/$transactionId'
    | '/school/staff/$teacherId'
    | '/school/staff/departments'
    | '/school/staff/schedule'
    | '/school/staff/subject-allocation'
    | '/school/staff/workload'
    | '/school/students/$studentId'
    | '/school/students/admissions'
    | '/school/students/guardians'
    | '/school/students/transfers'
    | '/admin/announcements/'
    | '/admin/billing/'
    | '/admin/onboarding/'
    | '/admin/schools/'
    | '/admin/support/'
    | '/school/finance/'
    | '/school/mpesa/'
    | '/school/staff/'
    | '/school/students/'
    | '/admin/billing/invoices/$invoiceId'
    | '/admin/billing/payments/$paymentId'
    | '/admin/billing/plans/$planId'
    | '/admin/billing/subscriptions/$subscriptionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/school'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/governance'
    | '/admin/security'
    | '/admin/settings'
    | '/school/cbc'
    | '/school/dashboard'
    | '/school/exams'
    | '/school/nemis'
    | '/school/settings'
    | '/school/tenant-configuration'
    | '/school/timetable'
    | '/admin/announcements/$announcementId'
    | '/admin/onboarding/$onboardingId'
    | '/admin/schools/$schoolId'
    | '/admin/support/$ticketId'
    | '/school/finance/$receiptId'
    | '/school/finance/defaulters'
    | '/school/mpesa/$transactionId'
    | '/school/staff/$teacherId'
    | '/school/staff/departments'
    | '/school/staff/schedule'
    | '/school/staff/subject-allocation'
    | '/school/staff/workload'
    | '/school/students/$studentId'
    | '/school/students/admissions'
    | '/school/students/guardians'
    | '/school/students/transfers'
    | '/admin/announcements'
    | '/admin/billing'
    | '/admin/onboarding'
    | '/admin/schools'
    | '/admin/support'
    | '/school/finance'
    | '/school/mpesa'
    | '/school/staff'
    | '/school/students'
    | '/admin/billing/invoices/$invoiceId'
    | '/admin/billing/payments/$paymentId'
    | '/admin/billing/plans/$planId'
    | '/admin/billing/subscriptions/$subscriptionId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/school'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/billing'
    | '/admin/dashboard'
    | '/admin/governance'
    | '/admin/onboarding'
    | '/admin/schools'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/support'
    | '/school/cbc'
    | '/school/dashboard'
    | '/school/exams'
    | '/school/finance'
    | '/school/mpesa'
    | '/school/nemis'
    | '/school/settings'
    | '/school/staff'
    | '/school/students'
    | '/school/tenant-configuration'
    | '/school/timetable'
    | '/admin/announcements/$announcementId'
    | '/admin/onboarding/$onboardingId'
    | '/admin/schools/$schoolId'
    | '/admin/support/$ticketId'
    | '/school/finance/$receiptId'
    | '/school/finance/defaulters'
    | '/school/mpesa/$transactionId'
    | '/school/staff/$teacherId'
    | '/school/staff/departments'
    | '/school/staff/schedule'
    | '/school/staff/subject-allocation'
    | '/school/staff/workload'
    | '/school/students/$studentId'
    | '/school/students/admissions'
    | '/school/students/guardians'
    | '/school/students/transfers'
    | '/admin/announcements/'
    | '/admin/billing/'
    | '/admin/onboarding/'
    | '/admin/schools/'
    | '/admin/support/'
    | '/school/finance/'
    | '/school/mpesa/'
    | '/school/staff/'
    | '/school/students/'
    | '/admin/billing/invoices/$invoiceId'
    | '/admin/billing/payments/$paymentId'
    | '/admin/billing/plans/$planId'
    | '/admin/billing/subscriptions/$subscriptionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  SchoolRoute: typeof SchoolRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/school': {
      id: '/school'
      path: '/school'
      fullPath: '/school'
      preLoaderRoute: typeof SchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school/timetable': {
      id: '/school/timetable'
      path: '/timetable'
      fullPath: '/school/timetable'
      preLoaderRoute: typeof SchoolTimetableRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/school/tenant-configuration': {
      id: '/school/tenant-configuration'
      path: '/tenant-configuration'
      fullPath: '/school/tenant-configuration'
      preLoaderRoute: typeof SchoolTenantConfigurationRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/school/students': {
      id: '/school/students'
      path: '/students'
      fullPath: '/school/students'
      preLoaderRoute: typeof SchoolStudentsRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/school/staff': {
      id: '/school/staff'
      path: '/staff'
      fullPath: '/school/staff'
      preLoaderRoute: typeof SchoolStaffRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/school/settings': {
      id: '/school/settings'
      path: '/settings'
      fullPath: '/school/settings'
      preLoaderRoute: typeof SchoolSettingsRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/school/nemis': {
      id: '/school/nemis'
      path: '/nemis'
      fullPath: '/school/nemis'
      preLoaderRoute: typeof SchoolNemisRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/school/mpesa': {
      id: '/school/mpesa'
      path: '/mpesa'
      fullPath: '/school/mpesa'
      preLoaderRoute: typeof SchoolMpesaRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/school/finance': {
      id: '/school/finance'
      path: '/finance'
      fullPath: '/school/finance'
      preLoaderRoute: typeof SchoolFinanceRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/school/exams': {
      id: '/school/exams'
      path: '/exams'
      fullPath: '/school/exams'
      preLoaderRoute: typeof SchoolExamsRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/school/dashboard': {
      id: '/school/dashboard'
      path: '/dashboard'
      fullPath: '/school/dashboard'
      preLoaderRoute: typeof SchoolDashboardRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/school/cbc': {
      id: '/school/cbc'
      path: '/cbc'
      fullPath: '/school/cbc'
      preLoaderRoute: typeof SchoolCbcRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schools': {
      id: '/admin/schools'
      path: '/schools'
      fullPath: '/admin/schools'
      preLoaderRoute: typeof AdminSchoolsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/onboarding': {
      id: '/admin/onboarding'
      path: '/onboarding'
      fullPath: '/admin/onboarding'
      preLoaderRoute: typeof AdminOnboardingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/governance': {
      id: '/admin/governance'
      path: '/governance'
      fullPath: '/admin/governance'
      preLoaderRoute: typeof AdminGovernanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/school/students/': {
      id: '/school/students/'
      path: '/'
      fullPath: '/school/students/'
      preLoaderRoute: typeof SchoolStudentsIndexRouteImport
      parentRoute: typeof SchoolStudentsRoute
    }
    '/school/staff/': {
      id: '/school/staff/'
      path: '/'
      fullPath: '/school/staff/'
      preLoaderRoute: typeof SchoolStaffIndexRouteImport
      parentRoute: typeof SchoolStaffRoute
    }
    '/school/mpesa/': {
      id: '/school/mpesa/'
      path: '/'
      fullPath: '/school/mpesa/'
      preLoaderRoute: typeof SchoolMpesaIndexRouteImport
      parentRoute: typeof SchoolMpesaRoute
    }
    '/school/finance/': {
      id: '/school/finance/'
      path: '/'
      fullPath: '/school/finance/'
      preLoaderRoute: typeof SchoolFinanceIndexRouteImport
      parentRoute: typeof SchoolFinanceRoute
    }
    '/admin/support/': {
      id: '/admin/support/'
      path: '/'
      fullPath: '/admin/support/'
      preLoaderRoute: typeof AdminSupportIndexRouteImport
      parentRoute: typeof AdminSupportRoute
    }
    '/admin/schools/': {
      id: '/admin/schools/'
      path: '/'
      fullPath: '/admin/schools/'
      preLoaderRoute: typeof AdminSchoolsIndexRouteImport
      parentRoute: typeof AdminSchoolsRoute
    }
    '/admin/onboarding/': {
      id: '/admin/onboarding/'
      path: '/'
      fullPath: '/admin/onboarding/'
      preLoaderRoute: typeof AdminOnboardingIndexRouteImport
      parentRoute: typeof AdminOnboardingRoute
    }
    '/admin/billing/': {
      id: '/admin/billing/'
      path: '/'
      fullPath: '/admin/billing/'
      preLoaderRoute: typeof AdminBillingIndexRouteImport
      parentRoute: typeof AdminBillingRoute
    }
    '/admin/announcements/': {
      id: '/admin/announcements/'
      path: '/'
      fullPath: '/admin/announcements/'
      preLoaderRoute: typeof AdminAnnouncementsIndexRouteImport
      parentRoute: typeof AdminAnnouncementsRoute
    }
    '/school/students/transfers': {
      id: '/school/students/transfers'
      path: '/transfers'
      fullPath: '/school/students/transfers'
      preLoaderRoute: typeof SchoolStudentsTransfersRouteImport
      parentRoute: typeof SchoolStudentsRoute
    }
    '/school/students/guardians': {
      id: '/school/students/guardians'
      path: '/guardians'
      fullPath: '/school/students/guardians'
      preLoaderRoute: typeof SchoolStudentsGuardiansRouteImport
      parentRoute: typeof SchoolStudentsRoute
    }
    '/school/students/admissions': {
      id: '/school/students/admissions'
      path: '/admissions'
      fullPath: '/school/students/admissions'
      preLoaderRoute: typeof SchoolStudentsAdmissionsRouteImport
      parentRoute: typeof SchoolStudentsRoute
    }
    '/school/students/$studentId': {
      id: '/school/students/$studentId'
      path: '/$studentId'
      fullPath: '/school/students/$studentId'
      preLoaderRoute: typeof SchoolStudentsStudentIdRouteImport
      parentRoute: typeof SchoolStudentsRoute
    }
    '/school/staff/workload': {
      id: '/school/staff/workload'
      path: '/workload'
      fullPath: '/school/staff/workload'
      preLoaderRoute: typeof SchoolStaffWorkloadRouteImport
      parentRoute: typeof SchoolStaffRoute
    }
    '/school/staff/subject-allocation': {
      id: '/school/staff/subject-allocation'
      path: '/subject-allocation'
      fullPath: '/school/staff/subject-allocation'
      preLoaderRoute: typeof SchoolStaffSubjectAllocationRouteImport
      parentRoute: typeof SchoolStaffRoute
    }
    '/school/staff/schedule': {
      id: '/school/staff/schedule'
      path: '/schedule'
      fullPath: '/school/staff/schedule'
      preLoaderRoute: typeof SchoolStaffScheduleRouteImport
      parentRoute: typeof SchoolStaffRoute
    }
    '/school/staff/departments': {
      id: '/school/staff/departments'
      path: '/departments'
      fullPath: '/school/staff/departments'
      preLoaderRoute: typeof SchoolStaffDepartmentsRouteImport
      parentRoute: typeof SchoolStaffRoute
    }
    '/school/staff/$teacherId': {
      id: '/school/staff/$teacherId'
      path: '/$teacherId'
      fullPath: '/school/staff/$teacherId'
      preLoaderRoute: typeof SchoolStaffTeacherIdRouteImport
      parentRoute: typeof SchoolStaffRoute
    }
    '/school/mpesa/$transactionId': {
      id: '/school/mpesa/$transactionId'
      path: '/$transactionId'
      fullPath: '/school/mpesa/$transactionId'
      preLoaderRoute: typeof SchoolMpesaTransactionIdRouteImport
      parentRoute: typeof SchoolMpesaRoute
    }
    '/school/finance/defaulters': {
      id: '/school/finance/defaulters'
      path: '/defaulters'
      fullPath: '/school/finance/defaulters'
      preLoaderRoute: typeof SchoolFinanceDefaultersRouteImport
      parentRoute: typeof SchoolFinanceRoute
    }
    '/school/finance/$receiptId': {
      id: '/school/finance/$receiptId'
      path: '/$receiptId'
      fullPath: '/school/finance/$receiptId'
      preLoaderRoute: typeof SchoolFinanceReceiptIdRouteImport
      parentRoute: typeof SchoolFinanceRoute
    }
    '/admin/support/$ticketId': {
      id: '/admin/support/$ticketId'
      path: '/$ticketId'
      fullPath: '/admin/support/$ticketId'
      preLoaderRoute: typeof AdminSupportTicketIdRouteImport
      parentRoute: typeof AdminSupportRoute
    }
    '/admin/schools/$schoolId': {
      id: '/admin/schools/$schoolId'
      path: '/$schoolId'
      fullPath: '/admin/schools/$schoolId'
      preLoaderRoute: typeof AdminSchoolsSchoolIdRouteImport
      parentRoute: typeof AdminSchoolsRoute
    }
    '/admin/onboarding/$onboardingId': {
      id: '/admin/onboarding/$onboardingId'
      path: '/$onboardingId'
      fullPath: '/admin/onboarding/$onboardingId'
      preLoaderRoute: typeof AdminOnboardingOnboardingIdRouteImport
      parentRoute: typeof AdminOnboardingRoute
    }
    '/admin/announcements/$announcementId': {
      id: '/admin/announcements/$announcementId'
      path: '/$announcementId'
      fullPath: '/admin/announcements/$announcementId'
      preLoaderRoute: typeof AdminAnnouncementsAnnouncementIdRouteImport
      parentRoute: typeof AdminAnnouncementsRoute
    }
    '/admin/billing/subscriptions/$subscriptionId': {
      id: '/admin/billing/subscriptions/$subscriptionId'
      path: '/subscriptions/$subscriptionId'
      fullPath: '/admin/billing/subscriptions/$subscriptionId'
      preLoaderRoute: typeof AdminBillingSubscriptionsSubscriptionIdRouteImport
      parentRoute: typeof AdminBillingRoute
    }
    '/admin/billing/plans/$planId': {
      id: '/admin/billing/plans/$planId'
      path: '/plans/$planId'
      fullPath: '/admin/billing/plans/$planId'
      preLoaderRoute: typeof AdminBillingPlansPlanIdRouteImport
      parentRoute: typeof AdminBillingRoute
    }
    '/admin/billing/payments/$paymentId': {
      id: '/admin/billing/payments/$paymentId'
      path: '/payments/$paymentId'
      fullPath: '/admin/billing/payments/$paymentId'
      preLoaderRoute: typeof AdminBillingPaymentsPaymentIdRouteImport
      parentRoute: typeof AdminBillingRoute
    }
    '/admin/billing/invoices/$invoiceId': {
      id: '/admin/billing/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/admin/billing/invoices/$invoiceId'
      preLoaderRoute: typeof AdminBillingInvoicesInvoiceIdRouteImport
      parentRoute: typeof AdminBillingRoute
    }
  }
}

interface AdminAnnouncementsRouteChildren {
  AdminAnnouncementsAnnouncementIdRoute: typeof AdminAnnouncementsAnnouncementIdRoute
  AdminAnnouncementsIndexRoute: typeof AdminAnnouncementsIndexRoute
}

const AdminAnnouncementsRouteChildren: AdminAnnouncementsRouteChildren = {
  AdminAnnouncementsAnnouncementIdRoute: AdminAnnouncementsAnnouncementIdRoute,
  AdminAnnouncementsIndexRoute: AdminAnnouncementsIndexRoute,
}

const AdminAnnouncementsRouteWithChildren =
  AdminAnnouncementsRoute._addFileChildren(AdminAnnouncementsRouteChildren)

interface AdminBillingRouteChildren {
  AdminBillingIndexRoute: typeof AdminBillingIndexRoute
  AdminBillingInvoicesInvoiceIdRoute: typeof AdminBillingInvoicesInvoiceIdRoute
  AdminBillingPaymentsPaymentIdRoute: typeof AdminBillingPaymentsPaymentIdRoute
  AdminBillingPlansPlanIdRoute: typeof AdminBillingPlansPlanIdRoute
  AdminBillingSubscriptionsSubscriptionIdRoute: typeof AdminBillingSubscriptionsSubscriptionIdRoute
}

const AdminBillingRouteChildren: AdminBillingRouteChildren = {
  AdminBillingIndexRoute: AdminBillingIndexRoute,
  AdminBillingInvoicesInvoiceIdRoute: AdminBillingInvoicesInvoiceIdRoute,
  AdminBillingPaymentsPaymentIdRoute: AdminBillingPaymentsPaymentIdRoute,
  AdminBillingPlansPlanIdRoute: AdminBillingPlansPlanIdRoute,
  AdminBillingSubscriptionsSubscriptionIdRoute:
    AdminBillingSubscriptionsSubscriptionIdRoute,
}

const AdminBillingRouteWithChildren = AdminBillingRoute._addFileChildren(
  AdminBillingRouteChildren,
)

interface AdminOnboardingRouteChildren {
  AdminOnboardingOnboardingIdRoute: typeof AdminOnboardingOnboardingIdRoute
  AdminOnboardingIndexRoute: typeof AdminOnboardingIndexRoute
}

const AdminOnboardingRouteChildren: AdminOnboardingRouteChildren = {
  AdminOnboardingOnboardingIdRoute: AdminOnboardingOnboardingIdRoute,
  AdminOnboardingIndexRoute: AdminOnboardingIndexRoute,
}

const AdminOnboardingRouteWithChildren = AdminOnboardingRoute._addFileChildren(
  AdminOnboardingRouteChildren,
)

interface AdminSchoolsRouteChildren {
  AdminSchoolsSchoolIdRoute: typeof AdminSchoolsSchoolIdRoute
  AdminSchoolsIndexRoute: typeof AdminSchoolsIndexRoute
}

const AdminSchoolsRouteChildren: AdminSchoolsRouteChildren = {
  AdminSchoolsSchoolIdRoute: AdminSchoolsSchoolIdRoute,
  AdminSchoolsIndexRoute: AdminSchoolsIndexRoute,
}

const AdminSchoolsRouteWithChildren = AdminSchoolsRoute._addFileChildren(
  AdminSchoolsRouteChildren,
)

interface AdminSupportRouteChildren {
  AdminSupportTicketIdRoute: typeof AdminSupportTicketIdRoute
  AdminSupportIndexRoute: typeof AdminSupportIndexRoute
}

const AdminSupportRouteChildren: AdminSupportRouteChildren = {
  AdminSupportTicketIdRoute: AdminSupportTicketIdRoute,
  AdminSupportIndexRoute: AdminSupportIndexRoute,
}

const AdminSupportRouteWithChildren = AdminSupportRoute._addFileChildren(
  AdminSupportRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRouteWithChildren
  AdminBillingRoute: typeof AdminBillingRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminGovernanceRoute: typeof AdminGovernanceRoute
  AdminOnboardingRoute: typeof AdminOnboardingRouteWithChildren
  AdminSchoolsRoute: typeof AdminSchoolsRouteWithChildren
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRouteWithChildren,
  AdminBillingRoute: AdminBillingRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminGovernanceRoute: AdminGovernanceRoute,
  AdminOnboardingRoute: AdminOnboardingRouteWithChildren,
  AdminSchoolsRoute: AdminSchoolsRouteWithChildren,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SchoolFinanceRouteChildren {
  SchoolFinanceReceiptIdRoute: typeof SchoolFinanceReceiptIdRoute
  SchoolFinanceDefaultersRoute: typeof SchoolFinanceDefaultersRoute
  SchoolFinanceIndexRoute: typeof SchoolFinanceIndexRoute
}

const SchoolFinanceRouteChildren: SchoolFinanceRouteChildren = {
  SchoolFinanceReceiptIdRoute: SchoolFinanceReceiptIdRoute,
  SchoolFinanceDefaultersRoute: SchoolFinanceDefaultersRoute,
  SchoolFinanceIndexRoute: SchoolFinanceIndexRoute,
}

const SchoolFinanceRouteWithChildren = SchoolFinanceRoute._addFileChildren(
  SchoolFinanceRouteChildren,
)

interface SchoolMpesaRouteChildren {
  SchoolMpesaTransactionIdRoute: typeof SchoolMpesaTransactionIdRoute
  SchoolMpesaIndexRoute: typeof SchoolMpesaIndexRoute
}

const SchoolMpesaRouteChildren: SchoolMpesaRouteChildren = {
  SchoolMpesaTransactionIdRoute: SchoolMpesaTransactionIdRoute,
  SchoolMpesaIndexRoute: SchoolMpesaIndexRoute,
}

const SchoolMpesaRouteWithChildren = SchoolMpesaRoute._addFileChildren(
  SchoolMpesaRouteChildren,
)

interface SchoolStaffRouteChildren {
  SchoolStaffTeacherIdRoute: typeof SchoolStaffTeacherIdRoute
  SchoolStaffDepartmentsRoute: typeof SchoolStaffDepartmentsRoute
  SchoolStaffScheduleRoute: typeof SchoolStaffScheduleRoute
  SchoolStaffSubjectAllocationRoute: typeof SchoolStaffSubjectAllocationRoute
  SchoolStaffWorkloadRoute: typeof SchoolStaffWorkloadRoute
  SchoolStaffIndexRoute: typeof SchoolStaffIndexRoute
}

const SchoolStaffRouteChildren: SchoolStaffRouteChildren = {
  SchoolStaffTeacherIdRoute: SchoolStaffTeacherIdRoute,
  SchoolStaffDepartmentsRoute: SchoolStaffDepartmentsRoute,
  SchoolStaffScheduleRoute: SchoolStaffScheduleRoute,
  SchoolStaffSubjectAllocationRoute: SchoolStaffSubjectAllocationRoute,
  SchoolStaffWorkloadRoute: SchoolStaffWorkloadRoute,
  SchoolStaffIndexRoute: SchoolStaffIndexRoute,
}

const SchoolStaffRouteWithChildren = SchoolStaffRoute._addFileChildren(
  SchoolStaffRouteChildren,
)

interface SchoolStudentsRouteChildren {
  SchoolStudentsStudentIdRoute: typeof SchoolStudentsStudentIdRoute
  SchoolStudentsAdmissionsRoute: typeof SchoolStudentsAdmissionsRoute
  SchoolStudentsGuardiansRoute: typeof SchoolStudentsGuardiansRoute
  SchoolStudentsTransfersRoute: typeof SchoolStudentsTransfersRoute
  SchoolStudentsIndexRoute: typeof SchoolStudentsIndexRoute
}

const SchoolStudentsRouteChildren: SchoolStudentsRouteChildren = {
  SchoolStudentsStudentIdRoute: SchoolStudentsStudentIdRoute,
  SchoolStudentsAdmissionsRoute: SchoolStudentsAdmissionsRoute,
  SchoolStudentsGuardiansRoute: SchoolStudentsGuardiansRoute,
  SchoolStudentsTransfersRoute: SchoolStudentsTransfersRoute,
  SchoolStudentsIndexRoute: SchoolStudentsIndexRoute,
}

const SchoolStudentsRouteWithChildren = SchoolStudentsRoute._addFileChildren(
  SchoolStudentsRouteChildren,
)

interface SchoolRouteChildren {
  SchoolCbcRoute: typeof SchoolCbcRoute
  SchoolDashboardRoute: typeof SchoolDashboardRoute
  SchoolExamsRoute: typeof SchoolExamsRoute
  SchoolFinanceRoute: typeof SchoolFinanceRouteWithChildren
  SchoolMpesaRoute: typeof SchoolMpesaRouteWithChildren
  SchoolNemisRoute: typeof SchoolNemisRoute
  SchoolSettingsRoute: typeof SchoolSettingsRoute
  SchoolStaffRoute: typeof SchoolStaffRouteWithChildren
  SchoolStudentsRoute: typeof SchoolStudentsRouteWithChildren
  SchoolTenantConfigurationRoute: typeof SchoolTenantConfigurationRoute
  SchoolTimetableRoute: typeof SchoolTimetableRoute
}

const SchoolRouteChildren: SchoolRouteChildren = {
  SchoolCbcRoute: SchoolCbcRoute,
  SchoolDashboardRoute: SchoolDashboardRoute,
  SchoolExamsRoute: SchoolExamsRoute,
  SchoolFinanceRoute: SchoolFinanceRouteWithChildren,
  SchoolMpesaRoute: SchoolMpesaRouteWithChildren,
  SchoolNemisRoute: SchoolNemisRoute,
  SchoolSettingsRoute: SchoolSettingsRoute,
  SchoolStaffRoute: SchoolStaffRouteWithChildren,
  SchoolStudentsRoute: SchoolStudentsRouteWithChildren,
  SchoolTenantConfigurationRoute: SchoolTenantConfigurationRoute,
  SchoolTimetableRoute: SchoolTimetableRoute,
}

const SchoolRouteWithChildren =
  SchoolRoute._addFileChildren(SchoolRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  SchoolRoute: SchoolRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
